### ISSUE TITLE
Pre-processing site filters too stringent

### ISSUE THREAD

**Issue by winni2k** [cbg-ethz/SCIPhI#15]
Thank you for a really exciting tool!

I have been playing around with sciphi, and I have found the site filters in the [`readMpileupFile` function](https://github.com/cbg-ethz/SCIPhI/blob/master/src/readData.h#L761) (i.e. the pre-processing filters) to be more stringent than I would like. In particular, it appears that in my data (140 normal human samples at 15x coverage), many sites that are clearly doubleton sites and that are called as variants by `bcftools mpileup/call` are being filtered out in the pre-processing stage [here](https://github.com/cbg-ethz/SCIPhI/blob/master/src/readData.h#L938-L943). 

I have two questions: 
1. Where in the SCIPhI paper is the filtering step described that is implemented in [`computeProbCellsAreMutated`](https://github.com/cbg-ethz/SCIPhI/blob/master/src/readData.h#L690), and what is its motivation?
2. Do you think that this filtering step could be removed without substantially changing the way that sciphi works?

Thanks again for this exciting scientific contribution.

**Comment by singerj** [comment]
Hi, 

Thank you for your interest in SCIPhI.

I am not entirely sure what you mean with doubleton sites. Are you referring to heterozygous sites with different alleles on the two chromosomes? 

In order to identify these sites SCIPhI computes the probability that at least x (default 2) cells show the mutation. We use the function computeProbCellsAreMutated to do so. The function iteratively computes the probability that no cell is mutated, one cell is mutated, two cells are mutated, and so on. We use a dynamic programming approach to realise the function which we do not explain in detail but which has also been used in other publications, for example, doi.org/10.1038/nmeth.3835 and doi.org/10.1101/gr.113084.110.
We chose x to be 2 as it is very challenging to distinguish between sequencing errors and mutations that occurred only in a single cell. However, setting --cwm 1 this can be changed to one, a very very liberal setting. 

It could also be that your mutations are not identified because they show a consistently low frequency across all mutated cells, for example, all cells show one or two nucleotides of the mutated allele at a coverage of around 10. As such an observation might very well be explained by alignment problems or sequencing artefacts they are filtered out. The filtering is based on learning two beta-binomial distributions, one with a fixed mean at m, and comparing if the observed nucleotide frequencies can be better explained with a mean different from m (this is also explained in the supplements). The default value for m is 0.25, but this can be changed setting --mff 0.01, for example. 

I hope this helps!
Jochen

**Comment by winni2k** [comment]
Dear Jochen,

Thank you very much for your response.

By doubleton I mean a variant that is shared by exactly two samples. Doubleton is an analogy to the word singleton as used in for example doi.org/10.1101/gr.113084.110.

I will see if the `--cwm` and `--mff` flags work for me.

One thing that is still not clear to me is this phrase that I think is also used in the SCIPhI paper:

> We use a dynamic programming approach to realise the function which we do not explain in detail but which has also been used in other publications, for example, doi.org/10.1038/nmeth.3835 and doi.org/10.1101/gr.113084.110.

Does SCIPhI implement the same function for estimating the probability that `n` cells are mutated  as the NLDA function described by Le and Durbin in doi.org/10.1101/gr.113084.110? Or does SCIPhI merely use a dynamic programming algorithm to solve a different but similar function to the one described by Le and Durbin?

Thanks,
Winni

**Comment by singerj** [comment]
Dear Winni,

Thanks for the clarification. 

SCIPhI does not implement the same function as used in Le and Durbin, where actually all possible allele configurations are checked. Instead, we are only interested in if there is a mutation or not. Therefore, instead of computing all different allele configurations we compute all possible combinations of exactly one cell being mutated, two cells being mutated, and so on. For example, when we compute the likelihood that one cell is mutated, it could be the first one, the second one, and so on. When computing the likelihood that two cells are mutated, it could be the first and the second, the first and the third, the second and the third, and so on. The whole process is depicted below.

[compute_porb.pdf](https://github.com/cbg-ethz/SCIPhI/files/3537490/compute_porb.pdf)

I hope this helps!

All the best,
Jochen

**Comment by winni2k** [comment]
Dear Jochen,
Thank you very much for the clarification. This helps!

Best,
Winni
